import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import LayoutComponent from './components/LayoutComponent'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Frontend - React + NEXT.js',
  description: 'Generated by create next app Dummy',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      </head>
      <body>
        <LayoutComponent>
        {children}
        </LayoutComponent>
        <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="assets/js/main.js"></script>
      </body>
    </html>
  )
}
